# Site settings
title: Learning DSP
email: me@griffinmoe.com
description: >
  Online resources for learning digital signal processing and audio plugin design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://griffinmoe.com/learning-dsp" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ["CNAME", "README.md"]
