# Site settings
title: Learning DSP
description: >
  Online resources for learning digital signal processing and audio plugin design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://griffinmoe.com/learning-dsp" # the base hostname & protocol for your site
repo: "https://github.com/gmoe/learning-dsp"

# Build settings
markdown: kramdown
exclude: ["CNAME"]
